#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

// Include ENV constants
$envConfigFile = __DIR__ . '/config/env-local.php';
if (!file_exists($envConfigFile)) {
    exit("config/env-local.php does not exists.\r\n");
}
require($envConfigFile);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);

// Set manually aliases (because they were not set properly)
Yii::setAlias('@app', __DIR__ . '/');
Yii::setAlias('@runtime', __DIR__ . '/runtime');

$exitCode = $application->run();
exit($exitCode);
